version: '3.8'

services:
  # --- AMBIENTE DE HOMOLOGAÇÃO ---
  homologacao:
    build: .
    container_name: finance-homologacao
    restart: always
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      # Mapeia diretamente o arquivo de banco individual, preservando a pasta do container!
      - ./data/homologacao:/app/prisma/data

  # --- AMBIENTE DE PRODUÇÃO ---
  producao:
    build: .
    container_name: finance-producao
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      # Mapeia diretamente o arquivo de banco individual
      - ./data/producao:/app/prisma/data